// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ-sahYHXO2LQPDY-xO3xb6gXzarOLI_I',
    appId: '1:414078561802:web:80989de4eec231ee2a79f3',
    messagingSenderId: '414078561802',
    projectId: 'upturn-dashboard',
    authDomain: 'upturn-dashboard.firebaseapp.com',
    storageBucket: 'upturn-dashboard.appspot.com',
    measurementId: 'G-XBDMKQKFY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpJvGOt144gt3_N93D0zw7HytEu_28Tw',
    appId: '1:414078561802:android:d02d1c5629dac19f2a79f3',
    messagingSenderId: '414078561802',
    projectId: 'upturn-dashboard',
    storageBucket: 'upturn-dashboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRfWf1Zd0tdzRlm71nTVdOz1Ya8xJkMOM',
    appId: '1:414078561802:ios:886f4c923a996df92a79f3',
    messagingSenderId: '414078561802',
    projectId: 'upturn-dashboard',
    storageBucket: 'upturn-dashboard.appspot.com',
    iosBundleId: 'com.example.upturnDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRfWf1Zd0tdzRlm71nTVdOz1Ya8xJkMOM',
    appId: '1:414078561802:ios:df5a2bb2a976aa902a79f3',
    messagingSenderId: '414078561802',
    projectId: 'upturn-dashboard',
    storageBucket: 'upturn-dashboard.appspot.com',
    iosBundleId: 'com.example.upturnDashboard.RunnerTests',
  );
}
